create table hospital (
       id bigint generated by default as identity,
        bairro varchar(255) not null,
        cidade varchar(255) not null,
        cnpj varchar(18) not null,
        estado varchar(255) not null,
        nome varchar(255) not null,
        numero varchar(10) not null,
        rua varchar(255) not null,
        primary key (id)
    );

 create table ocupacao (
       id bigint generated by default as identity,
        percentual double not null,
        hospital_id bigint not null,
        primary key (id),
        foreign key (hospital_id) references hospital(id)
    );
    
 create table recurso (
       id bigint generated by default as identity,
        item varchar(255) not null,
        pontos integer not null,
        hospital_id bigint not null,
        primary key (id),
        foreign key (hospital_id) references hospital(id)
    );